
CFLAGS=-std=gnu99 -Wall -g

make:
	gcc -o ext2_mkdir ext2_mkdir.c
	gcc -o ext2_checker ext2_checker.c
	gcc -o ext2_cp ext2_cp.c	
	gcc -o ext2_rm ext2_rm.c
	gcc -o ext2_restore ext2_restore.c
	gcc -o ext2_ln ext2_ln.c
